// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatRefreshController from "./chat_refresh_controller"
application.register("chat-refresh", ChatRefreshController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InputResetController from "./input_reset_controller"
application.register("input-reset", InputResetController)
