services:
  web:
    build: .
    volumes:
      - bundle:/usr/local/bundle
      - .:/rails_app
    ports:
      - "3001:3000"
    tty: true
    stdin_open: true
    env_file:
      - .env.development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5445:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "7963:6379"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  pg_data:
  redis_data:
  bundle: